// Code generated by "stringer -type ClientState"; DO NOT EDIT.

package proxy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CsCreated-0]
	_ = x[CsInit-1]
	_ = x[CsActive-2]
	_ = x[CsSudo-3]
}

const _ClientState_name = "CsCreatedCsInitCsActiveCsSudo"

var _ClientState_index = [...]uint8{0, 9, 15, 23, 29}

func (i ClientState) String() string {
	if i >= ClientState(len(_ClientState_index)-1) {
		return "ClientState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientState_name[_ClientState_index[i]:_ClientState_index[i+1]]
}
