// Code generated by "stringer -type LeaveType"; DO NOT EDIT.

package proxy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Exit-0]
	_ = x[Kick-1]
}

const _LeaveType_name = "ExitKick"

var _LeaveType_index = [...]uint8{0, 4, 8}

func (i LeaveType) String() string {
	if i >= LeaveType(len(_LeaveType_index)-1) {
		return "LeaveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LeaveType_name[_LeaveType_index[i]:_LeaveType_index[i+1]]
}
